adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/', adminapp.ProductListView.as_view(), name='products'),
    path('products/read/category/<int:category_pk>/', adminapp.ProductListView.as_view(), name='products_by_category'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from django.conf.urls import include
if settings.DEBUG:
    import debug_toolbar



urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include( 'mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('deal/<int:pk>/', mainapp.deal, name='deal'),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('category/0/page/1', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
]

mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory (models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return  self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='в наличии', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)
    is_active = models.BooleanField(verbose_name='активен', default=True)
    def __str__(self):
        return "{} ({})".format(self.name, self.category.id)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
import json
from .models import Product, ProductCategory
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

with open("db.json", "r", encoding='utf-8') as read_file:
    data = json.load(read_file)

links_sec_menu = ProductCategory.objects.all()
titles = data['titles']

def main(request):
    products = Product.objects.all()
    hot_product = Product.objects.filter(is_hot=True).distinct().order_by('?')
    hot_product = hot_product[:3]
    content = {
                'titles': titles,
                'products_4': products[:4],
                'products_6': products[4:10],
                'products_22': products[10:14],
                'hot_product_2': hot_product[:2],
                'hot_product_1': hot_product[2],
            }
    return render(request, 'mainapp/index.html', content)

def products(request, pk=0, page=1):
    """products filter"""
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

        """hot_product"""
        hot_product = Product.objects.filter(is_hot=True).order_by('?')
        hot_product = hot_product[:2]

        """paginator"""
        paginator = Paginator(products, 6)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
                   'links_sec_menu': links_sec_menu,
                   'products': products_paginator,
                   'titles': titles,
                   'hot_product_2': hot_product,
                   'category': category,
                   }
        return render(request, 'mainapp/catalog.html', content)

def contact(request):
    content = {
                'titles': titles
              }
    return render(request, 'mainapp/contacts.html', content)

def deal(request, pk=None):
    product = Product.objects.filter(id=pk).first()
    products = Product.objects.all()[:3]
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    content = {
                'links_sec_menu': links_sec_menu,
                'titles': titles,
                'product': product,
                'products': products,
                'basket': basket
              }
    return render(request, 'mainapp/deal.html', content)

mainapp/templates/mainapp/includes/inc_menu.html
{% load staticfiles %}
{% block menu %}
    <ul class="menu">
            <li>
                <a href="{% url 'main' %}"
                    class="{% if request.resolver_match.url_name == 'main' %}
                        active
                        {% endif %}">
                    HOME
                </a>
            </li>
            <li>
                <a href="{% url 'products:page' 0 1 %}"
                    class="{% if request.resolver_match.namespace == 'products' %}
                        active
                        {% endif %}">
                    PRODUCTS
                </a>
            </li>
            <li>
                <a href="{% url 'contact' %}"
                    class="{% if request.resolver_match.url_name == 'contact' %}
                        active
                        {% endif %}">
                    CONTACTS
                </a>
            </li>
            <li>
                <a href="{% url 'basket:view' %}"
                    class="{% if request.resolver_match.url_name == 'basket' %}
                        active
                        {% endif %}">
                    BASKET
                </a>
            </li>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'auth:edit' request.user.id%}">
                        {{ user.first_name|default:'Пользователь' }}
                     </a>
                </li>
            {% endif %}
            {% if user.is_superuser %}
                <li>
                    <a href="{% url 'admin_custom:users' %}">админка</a>
                </li>
            {% endif %}
            <li>
                {% if user.is_authenticated %}
                    <a href="{% url 'auth:logout' %}">выйти</a>
                {% else %}
                    <a href="{% url 'auth:login' %}">войти</a>
                {% endif %}
            </li>
        <li><a href="{% url 'main' %}"><img src="{% static '/img/search.png' %}" alt="search"></a></li>
    </ul>
{% endblock %}

mainapp/templates/mainapp/includes/inc_prod_2.html
{% load staticfiles %}
{% load custom_tags %}
{% block prod_2 %}
    {% for prod in hot_product_2 %}
             <div class="col-lg-6 promo">
                    <img src="{{ prod.image|media_folder_products }}" alt="Картинка не прогрузилась">
                    <div class="slider-content">
                        <h3>exclusive</h3>
                        <h1>{{prod.name}}</h1>
                        <p>{{prod.description}}</p>
                        <a class="order" href="">
                            order us
                        </a>
                    </div>
             </div>
    {% endfor %}
{% endblock %}

mainapp/templates/mainapp/includes/inc_sec_menu.html
{% load staticfiles %}
{% block menu %}
    <div class="categories">
        <ul>
            {% for link in links_sec_menu %}
                <li><a href="{% url 'products:page' link.id 1 %}"
                       class="{% if request.resolver_match.kwargs.pk == link.id %}
                                 active
                              {% endif %}">
                       {{ link.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}