authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from django.conf.urls import include
if settings.DEBUG:
    import debug_toolbar



urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include( 'mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('deal/<int:pk>/', mainapp.deal, name='deal'),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from django.conf import settings
from mainapp.models import Product

class Basket(models.Model):
    class Meta:
        verbose_name = 'корзина'
        verbose_name_plural = 'корзины'

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='basket')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(verbose_name='количество', default=0)
    add_datetime = models.DateTimeField(verbose_name='время', auto_now_add=True)

    def __str__(self):
        return "{} - {}".format(self.user.username, self.product.name)

    def get_cost(self):
        return self.quantity * self.product.price

    cost = property(get_cost)

basketapp/views.py
from django.shortcuts import render, HttpResponseRedirect, get_object_or_404
from basketapp.models import Basket
from mainapp.models import Product
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse


@login_required
def basket(request):
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
        content = {
            'basket': basket,
        }
        return render(request, 'basketapp/basket.html', content)
    else:
        return HttpResponseRedirect(reverse('main'))

@login_required
def basket_add(request, pk):
    if 'login' in request.META.get('HTTP_REFERER'):
        return HttpResponseRedirect(reverse('deal', args=[pk]))
    product = get_object_or_404(Product, pk=pk)
    basket = Basket.objects.filter(user=request.user, product=product).first()
    if not basket:
        basket = Basket(user=request.user, product=product)
    basket.quantity += 1
    basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def basket_remove(request, pk):
    basket = get_object_or_404(Basket, pk=pk)
    if basket.quantity == 1:
        basket.delete()
    else:
        basket.quantity -= 1
        basket.save()


    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def basket_edit(request, pk):
    if request.is_ajax():
        basket_slot = get_object_or_404(Basket, pk=pk)
        quantity = int(request.GET.get('quantity'))
        if quantity > 0:
            basket_slot.quantity = quantity
            basket_slot.save()
        else:
            basket_slot.delete()

        basket_items = Basket.objects.filter(user=request.user).order_by('product__category')

        content = {
            'basket_items': basket_items,
        }

        result = render_to_string('basketapp/basket.html', content)

        return JsonResponse({'result': result})

basketapp/templates/basketapp/includes/inc_basket_list.html
{% for item in basket_items %}
        <img src="/media/{{ item.product.image }}" 
             alt="{{ item.product.short_desc }}">
        <span class="category_name">{{ item.product.category.name }}</span> 
        <span class="product_name">{{ item.product.name }}</span>
        <span class="product_price">{{ item.product.price }}&nbspруб</span>
        <input type="number" name="{{ item.pk }}" min="0" 
                             value="{{ item.quantity }}">
        <span class="product_cost">{{ item.cost }}&nbspруб</span>
        <button class="btn btn-round">
            <a href="{% url 'basket:remove' item.pk %}" class="">
                удалить
            </a>
        </button>
    </div>
{% endfor %}
<table class="table table-borderless">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Image</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Quantity</th>
          <th scope="col">Total  Price</th>
          <th></th>
        </tr>
      </thead>
<tbody>
       {% for prod in basket %}
        <tr>
          <th scope="row">{{ prod.id }}</th>
          <td><img src="../media/{{ prod.product.image }}" alt="Картинка не прогрузилась"></td>
          <td>{{ prod.product.name }}</td>
          <td>{{ prod.product.price }}</td>
          <td><input type="number" min="0" name="{{ prod.pk }}" value="{{ prod.quantity }}" title=" "></td>
          <td>{{ prod.cost }}</td>
          <td><a href="{% url 'basket:remove' prod.pk %}">Delete from cart</a> </td>
        </tr>
       {% endfor %}
      </tbody>


{% if basket_items %}
    <h3>Final price: {{ request.user|basket_total_cost }}</h3>
{% endif %}