authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('register/', authapp.register, name='register'),
    path('login/', authapp.login, name='login'),
    path('edit/<int:pk>/', authapp.EditView.as_view(), name='edit'),
    path('logout/', authapp.logout, name='logout')
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
import mainapp.views as mainapp
from django.conf.urls import include
if settings.DEBUG:
    import debug_toolbar



urlpatterns = [
    path('', mainapp.main, name='main'),
    path('products/', include( 'mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('admin/', admin.site.urls),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('deal/<int:pk>/', mainapp.deal, name='deal'),
    path('admin_custom/', include('adminapp.urls', namespace='admin_custom')),
    path('__debug__/', include(debug_toolbar.urls)),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('category/0/page/1', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
]

mainapp/models.py
from django.db import models

# Create your models here.

class ProductCategory (models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание', blank=True)
    is_active = models.BooleanField(verbose_name='активен', default=True)

    def __str__(self):
        return  self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='в наличии', default=0)
    is_hot = models.BooleanField(verbose_name='горячее предложение', default=False)
    is_active = models.BooleanField(verbose_name='активен', default=True)
    def __str__(self):
        return "{} ({})".format(self.name, self.category.id)

mainapp/views.py
from django.shortcuts import render, get_object_or_404
import json
from .models import Product, ProductCategory
from basketapp.models import Basket
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

with open("db.json", "r", encoding='utf-8') as read_file:
    data = json.load(read_file)

links_sec_menu = ProductCategory.objects.all()
titles = data['titles']

def main(request):
    products = Product.objects.all()
    hot_product = Product.objects.filter(is_hot=True).distinct().order_by('?')
    hot_product = hot_product[:3]
    content = {
                'titles': titles,
                'products_4': products[:4],
                'products_6': products[4:10],
                'products_22': products[10:14],
                'hot_product_2': hot_product[:2],
                'hot_product_1': hot_product[2],
            }
    return render(request, 'mainapp/index.html', content)

def products(request, pk=0, page=1):
    """products filter"""
    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все'
            }
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
        else:
            category = get_object_or_404(ProductCategory, pk=pk)
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

        """hot_product"""
        hot_product = Product.objects.filter(is_hot=True).order_by('?')
        hot_product = hot_product[:2]

        """paginator"""
        paginator = Paginator(products, 6)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
                   'links_sec_menu': links_sec_menu,
                   'products': products_paginator,
                   'titles': titles,
                   'hot_product_2': hot_product,
                   'category': category,
                   }
        return render(request, 'mainapp/catalog.html', content)

def contact(request):
    content = {
                'titles': titles
              }
    return render(request, 'mainapp/contacts.html', content)

def deal(request, pk=None):
    product = Product.objects.filter(id=pk).first()
    products = Product.objects.all()[:3]
    basket = []
    if request.user.is_authenticated:
        basket = Basket.objects.filter(user=request.user)
    content = {
                'links_sec_menu': links_sec_menu,
                'titles': titles,
                'product': product,
                'products': products,
                'basket': basket
              }
    return render(request, 'mainapp/deal.html', content)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load custom_tags %}
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    {% block css %}
        <link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    {% endblock %}
    {% block js %}
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endblock %}

    <title>
        {% block title %}
            {% for key, value in titles.items %}
                {% if key == request.resolver_match.url_name %}
                    {{ value }}
                {% endif %}
            {% endfor %}
        {% endblock %}
    </title>
</head>

<body>
    <div class="conteiner">
        <div class="user">
            {% if request.user.is_authenticated %}
                <h2>Пользователь: {{ request.user.username|title }}</h2>
                <a href="{% url 'auth:logout' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">logout</a>
                <a href="{% url 'auth:edit' request.user.id %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">edit profile</a>
                <a href="{% url 'basket:view' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">your cart</a>
                <h3> In your cart: {{ request.user|basket_total_quantity }} products fo the amount of {{ request.user|basket_total_cost }}</h3>

            {% else %}
                <h2>Пользователь не авторизован</h2>
                <a href="{% url 'auth:login' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">login</a>
                <a href="{% url 'auth:register' %}" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">create user</a>
            {% endif %}

        </div>
        <div class="header">
            {% block header %}
                <a href="{% url 'main' %}">
                    <img class="logo" src="{% static '/img/logo.png' %}" alt="Картинка не прогрузилась">
                </a>
                {% include 'mainapp/includes/inc_menu.html' %}
            {% endblock %}
        </div>
        <div class="content">
            {% block content %}

            {% endblock %}
        </div>
        <div class="footer">
            {% block footer %}
                <div class="contact">
                    <h2>Contact Us</h2>
                    <p>132A Bridge Road Richmond VIC
                        Australia.
                    </p>
                    <p>Talk to us on 1300 132
                        info@interior.com</p>
                </div>
                <div class="useful">
                    <h2>Useful Information</h2>
                    <ul>
                        <li><a href="{% url 'main' %}">Sales terms</a></li>
                        <li><a href="{% url 'main' %}">Customer care</a></li>
                        <li><a href="{% url 'main' %}">Delivery</a></li>
                    </ul>
                    <ul>
                        <li><a href="{% url 'main' %}">Architect accounts</a></li>
                        <li><a href="{% url 'main' %}">Careers</a></li>
                        <li><a href="{% url 'main' %}">Exchanges & returns</a></li>
                    </ul>
                </div>
                <div class="lets_stay">
                    <h2>Let’s Stay in Touch!</h2>
                    <p>Suscribe to know about our latest news, products and special offers just for suscribers.</p>
                    <input class="form" type="text" value="your email address">
                </div>
                <div class="copyright">
                    <p>© Copyright - INTERIOR 2016. All Rights Reserved.</p>
                </div>
                <div class="social"><img src="{% static '/img/social-links.png' %}" alt="Картинка не прогрузилась"></div>
                <div class="terms"><a href="{% url 'main' %}">Terms & Conditions / Privacy policy & Cookies</a></div>
            {% endblock %}
        </div>
    </div>
</body></html>

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load custom_tags %}
{% block css %}
    {{ block.super}}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_deals.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_contacts.css' %}">
{% endblock %}
{% block header %}
    {{block.super}}
    <h1>Our Products Range</h1>
{% endblock %}
{% block content %}
            {% include 'mainapp/includes/inc_sec_menu.html' %}
            {% for product in products %}
                {% if forloop.counter|add:2|divisibleby:3 %}
                    <div class="trends row row_3">
                {% endif %}
                    <div class="product col-lg-4">
                        <img src="{{ product.image|media_folder_products }}" alt="Картинка не прогрузилась">
                        <a href="{% url 'deal' product.id  %}">
                            <div class="ar_in"></div>
                            <h3>{{ product.name }}</h3>
                            <p>{{ product.short_desc }}</p>
                        </a>
                    </div>
                {% if forloop.counter|divisibleby:3 or forloop.last %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                        <
                    </a>
                {% endif %}
                <span class="current">
                    страница {{ products.number }} из {{ products.paginator.num_pages }}
                </span>
                {% if products.has_next %}
                    <a href="{% url 'products:page' category.pk products.next_page_number %}">
                        >
                    </a>
                {% endif %}
            </div>

            <div class="row level_2">
                {% include 'mainapp/includes/inc_prod_2.html' %}
            </div>
{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block css %}
    {{ block.super}}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_contacts.css' %}">
{% endblock %}
{% block header %}
    {{block.super}}
            <h1>Contact Us</h1>
{% endblock %}

{% block content %}
            <div class="block_3">
                <img src="{% static '/img/point.png' %}" alt="Картинка не прогрузилась">
                <h1>California</h1>
                <h2>Phone:</h2>
                <h3>1900 - 1234 -5678</h3>
                <h2>Email:</h2>
                <h3>info@interior.com</h3>
                <h2>Address:</h2>
                <p>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="block_3"><img src="{% static '/img/point.png' %}" alt="Картинка не прогрузилась">
                <h1>California</h1>
                <h2>Phone:</h2>
                <h3>1900 - 1234 -5678</h3>
                <h2>Email:</h2>
                <h3>info@interior.com</h3>
                <h2>Address:</h2>
                <p>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
            <div class="block_3"><img src="{% static '/img/point.png' %}" alt="Картинка не прогрузилась">
                <h1>California</h1>
                <h2>Phone:</h2>
                <h3>1900 - 1234 -5678</h3>
                <h2>Email:</h2>
                <h3>info@interior.com</h3>
                <h2>Address:</h2>
                <p>12 W 1st St, 90001 Los Angeles, California</p>
            </div>
{% endblock %}

mainapp/templates/mainapp/deal.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% block css %}
    {{ block.super}}
    <link rel="stylesheet" type="text/css" href="{% static '/css/style_deals.css' %}">
{% endblock %}
{% block content %}
            {% include 'mainapp/includes/inc_sec_menu.html' %}
            <div class="offer row">
                <div class="col-6">
                    <img src="../../media/{{ product.image }}" alt="Картинка не прогрузилась">
                </div>
                <div class="col-6">

                    <h1>{{ product.name }}</h1>
                    <h3>Hot Deal</h3>
                    <div class="sm">$</div>
                    <div class="big">{{ product.price }}</div>
                    <div class="sm">/sq</div>
                    <a href="{% url 'basket:add' product.pk %}"><span class="order">Add to cart</span></a>
                    <div class="text">
                        <p>{{ product.short_desc }}</p>
                        <p>{{ product.description }}</p>
                    </div>
                </div>
            </div>

            <div class="level_3 block_explore">
                <div class="row">
                    <div class="col-lg-6">
                        <h2>Trending Products</h2>
                    </div>
                    <div class="col-lg-6">
                        <a class="explore" href="{% url 'products:index' %}">
                            explore all
                        </a>
                    </div>
                </div>
                    {% for product in products %}
                        {% if forloop.counter == 1 or forloop.counter == 4 %}
                            <div class="row">
                        {% endif %}
                            <div class="col-lg-4 product row_3">
                                <img src="../../media/{{ product.image }}" alt="Картинка не прогрузилась">
                                <a href="{% url 'deal' product.id %}">
                                    <div class="ar_in"></div>
                                    <h3>{{ product.name }}</h3>
                                    <p>{{ product.short_desc }}</p>
                                </a>
                            </div>
                        {% if forloop.counter == 3 or forloop.counter == 6 %}
                           </div>
                        {% endif %}
                    {% endfor %}
            </div>
{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}
{% load  custom_tags%}
{% block header %}
    {{ block.super }}
    <div class="slider-content">
        <h3>trending</h3>
        <h1>Fishnet chair</h1>
        <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
            or highly polished chrome.</p>
        <a class="order" href="{% url 'products:index' %}">
            order us
        </a>
    </div>
    <div class="navi"></div>
{% endblock %}

{% block content %}
            <div class="block_explore level_1">
                <div class="row">
                    <div class="col-lg-6">
                        <ul class="menu">
                            <li><a href="{% url 'main' %}">Featured</a></li>
                            <li><a href="{% url 'main' %}">New</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-6">
                        <a class="explore" href="{% url 'products:index' %}">explore all</a>
                    </div>
                </div>
                <div class="row">
                    {% for product in products_4 %}
                        <div class="col-lg-3 product row_4">
                            <img src="{{ product.image|media_folder_products }}" alt="Картинка не прогрузилась">
                            <a href="{% url 'deal' product.id %}">
                                <div class="ar_in"></div>
                                <h3>{{ product.name }}</h3>
                                <p>{{ product.short_desc }}</p>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row level_2">
                {% include 'mainapp/includes/inc_prod_2.html' %}
            </div>
            <div class="level_3 block_explore">
                <div class="row">
                    <div class="col-lg-6">
                        <h2>Trending Products</h2>
                    </div>
                    <div class="col-lg-6">
                        <a class="explore" href="{% url 'products:index' %}">
                            explore all
                        </a>
                    </div>
                </div>
                    {% for product in products_6 %}
                        {% if forloop.counter == 1 or forloop.counter == 4 %}
                            <div class="row">
                        {% endif %}
                            <div class="col-lg-4 product row_3">
                                <img src="{{ product.image|media_folder_products }}" alt="Картинка не прогрузилась">
                                <a href="{% url 'deal' product.id %}">
                                    <div class="ar_in"></div>
                                    <h3>{{ product.name }}</h3>
                                    <p>{{ product.short_desc }}</p>
                                </a>
                            </div>
                        {% if forloop.counter == 3 or forloop.counter == 6 %}
                           </div>
                        {% endif %}
                    {% endfor %}
            </div>
            <div class="level_4">
                <div class="slider">
                    <img src="{% static '/img/slider.jpg' %}" alt="Картинка не прогрузилась">
                    <div class="slider-content">
                        <h3>Hot deal</h3>
                        <h1>Fishnet chair</h1>
                        <p>Seat and back with upholstery made of cold cure foam. Steel frame, available in matt powder-coated black
                            or highly polished chrome.</p>
                        <a class="order" href="{% url 'products:index' %}">
                            order us
                        </a>
                    </div>
                    <div class="navi"></div>
                </div>
            </div>
            <div class="level_5 row">
                <div class="col-lg-6 promo">
                    <img src="{{ hot_product_1.image|media_folder_products }}" alt="Картинка не прогрузилась">
                    <div class="slider-content">
                        <h3>exclusive</h3>
                        <h1>{{hot_product_1.name}}</h1>
                        <p>{{hot_product_1.description}}</p>
                        <a class="order" href="">
                            order us
                        </a>
                    </div>

                </div>
                <div class="col-lg-6">
                    {% for product in products_22 %}
                        {% if forloop.counter == 1 or forloop.counter == 3 %}
                            <div class="row">
                        {% endif %}
                            <div class="col-lg-6 right_bar">
                                <div class="product row_4">
                                    <img src="{{ product.image|media_folder_products }}" alt="Картинка не прогрузилась">
                                    <a href="{% url 'deal' product.id %}">
                                        <div class="ar_in">
                                        </div>
                                        <h3>{{ product.name }}</h3>
                                        <p>{{ product.short_desc }}</p>
                                    </a>
                                </div>
                            </div>
                        {% if forloop.counter == 2 or forloop.counter == 4 %}
                            </div>
                        {% endif %}
                    {% endfor %}
            </div>
            <div class="follow">
                <div class="slider-content">
                    <h3>mobile app</h3>
                    <h1>Find. Follow. Favorite.
                        Discover brands on the go.</h1>
                    <p>Save your favorites and share your style.</p>
                </div>
                <a class="first" href=""><img src="{% static '/img/app-store.jpg' %}" alt="Картинка не прогрузилась"></a>
                <a href="{% url 'main' %}"><img src="{% static '/img/google-play.jpg' %}" alt="Картинка не прогрузилась"></a>
            </div>
{% endblock %}